#!/bin/bash
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
# =============================================================================
# DreamZero LIBERO SFT Launch Script for Amazon EKS (Ray / FSDP2)
#
# Launches supervised fine-tuning of DreamZero (14B WAM) on LIBERO using
# upstream RLinf's new SFT mechanism: the entrypoint examples/sft/train_vla_sft.py
# driven by RLinf's Cluster (Ray) scheduler with FSDP2.
#
# This script runs on the Ray HEAD pod AFTER the Ray workers have joined.
# RLinf's Cluster scheduler fans the training out across all nodes/GPUs in the
# Ray cluster, so this launcher does NOT use torchrun -- it simply invokes the
# Hydra-driven entrypoint once on the head.
#
# Key environment variables (set via K8s manifest env):
#   VENV_NAME       - Python venv to activate (default: dreamzero)
#   CONFIG_NAME     - Hydra config name (default: libero_sft_dreamzero_14b)
#   MODEL_PATH      - 14B warm-start checkpoint (default: /fsx/models/DreamZero-DROID)
#   TOKENIZER_PATH  - umt5-xxl tokenizer (default: /fsx/models/umt5-xxl)
#   DATASET_PATH    - LeRobot-layout LIBERO dataset (default: /fsx/datasets/libero)
#   METADATA_PATH   - LIBERO normalization metadata.json
#                     (default: /fsx/models/metadata-libero.json, generated by
#                     generate-metadata.yaml). Set empty to fall back to the
#                     checkpoint's bundled metadata (oxe_droid only).
#   CKPT_PATH       - Path to write checkpoints (default: /fsx/checkpoints)
#   EXPERIMENT_NAME - Experiment / log dir name (default: dreamzero-libero-sft)
#   NUM_NODES       - Number of nodes in the Ray cluster (default: 2)
#   HYDRA_OVERRIDES - Extra Hydra overrides (e.g. "runner.max_steps=1")
# =============================================================================
set -euo pipefail
set -x

# --- Configuration (override via environment variables) ---
VENV_NAME="${VENV_NAME:-dreamzero}"
CONFIG_NAME="${CONFIG_NAME:-libero_sft_dreamzero_14b}"

MODEL_PATH="${MODEL_PATH:-/fsx/models/DreamZero-DROID}"
TOKENIZER_PATH="${TOKENIZER_PATH:-/fsx/models/umt5-xxl}"
DATASET_PATH="${DATASET_PATH:-/fsx/datasets/libero}"
METADATA_PATH="${METADATA_PATH:-/fsx/models/metadata-libero.json}"
CKPT_PATH="${CKPT_PATH:-/fsx/checkpoints}"
EXPERIMENT_NAME="${EXPERIMENT_NAME:-dreamzero-libero-sft}"

NUM_NODES="${NUM_NODES:-2}"

# --- Activate the correct venv ---
# Upstream RLinf images use the multi-venv pattern (uv). DreamZero LIBERO SFT
# runs in the dedicated 'dreamzero' venv. Pre-set PYTHONPATH before sourcing the activate
# script so it does not trip the "unbound variable" guard under set -u
# (documented gotcha in examples/AGENTS.md).
export PYTHONPATH="${PYTHONPATH:-}"
UV_PATH="${UV_PATH:-/opt/venv}"

if [ -f "${UV_PATH}/${VENV_NAME}/bin/activate" ]; then
    echo "Activating venv: ${VENV_NAME}"
    source "${UV_PATH}/${VENV_NAME}/bin/activate"
elif [ -f "/usr/local/bin/switch_env" ]; then
    echo "Activating venv via switch_env: ${VENV_NAME}"
    source switch_env "${VENV_NAME}"
else
    echo "WARNING: No venv found for ${VENV_NAME}, using system Python"
fi

echo "Python: $(which python3)"
echo "PyTorch: $(python3 -c 'import torch; print(torch.__version__)' 2>/dev/null || echo 'not found')"

# --- DreamZero groot package on PYTHONPATH ---
export DREAMZERO_PATH="${DREAMZERO_PATH:-/workspace/DreamZero}"
export PYTHONPATH="${DREAMZERO_PATH}:${PYTHONPATH}"

# --- EMBODIED_PATH for Hydra searchpath interpolation ---
# Upstream SFT configs interpolate this to resolve the config searchpath.
export EMBODIED_PATH="${EMBODIED_PATH:-/workspace/RLinf/examples/sft}"

# --- Headless rendering defaults ---
# SFT may not need GL, but osmesa is the safe EKS default and matches the eval
# path (avoids EGL/driver surprises if any sim import touches rendering).
export MUJOCO_GL="${MUJOCO_GL:-osmesa}"
export PYOPENGL_PLATFORM="${PYOPENGL_PLATFORM:-osmesa}"

# --- Pre-flight checks: verify staged inputs exist ---
for p in "${MODEL_PATH}" "${TOKENIZER_PATH}" "${DATASET_PATH}"; do
    if [ ! -e "${p}" ]; then
        echo "ERROR: required path not found: ${p}"
        echo "Run the model-download / staging job first."
        exit 1
    fi
done

# --- Launch training ---
cd /workspace/RLinf

LOG_DIR="${CKPT_PATH}/${EXPERIMENT_NAME}"
mkdir -p "${LOG_DIR}"

# Build Hydra override args (space-separated). These keys match the upstream
# libero_sft_dreamzero_14b.yaml structure.
HYDRA_ARGS="actor.model.model_path=${MODEL_PATH}"
HYDRA_ARGS="${HYDRA_ARGS} actor.model.tokenizer_path=${TOKENIZER_PATH}"
HYDRA_ARGS="${HYDRA_ARGS} data.train_data_paths=${DATASET_PATH}"
HYDRA_ARGS="${HYDRA_ARGS} cluster.num_nodes=${NUM_NODES}"
HYDRA_ARGS="${HYDRA_ARGS} runner.logger.log_path=${LOG_DIR}"

# NOTE on checkpoint format for eval:
# RLinf's FSDP saver writes a sharded DCP checkpoint (.distcp + .metadata) under
#   {ckpt}/actor/dcp_checkpoint/. The LIBERO eval needs a single .pt; convert the
# DCP to .pt offline (CPU) with kubernetes/libero/convert-checkpoint.yaml.
# We do NOT use +actor.fsdp_config.save_full_model_weights=true: on 2x p5en the
# rank-0 full-state-dict gather for the 16B model is pathologically slow / stalls.
# DCP-only save + offline convert is faster and more reliable.
# IMPORTANT: ensure FSx has ample free space (>=200GB for a 14B DCP checkpoint);
# a full filesystem truncates torch.save mid-write (inline_container.cc
# "unexpected pos") producing corrupt, unreadable shards.

# Temporal alignment fix: libero_sft_dreamzero_14b.yaml sets action_horizon=16
# but inherits num_action_per_block=24 from model/dreamzero_14b.yaml (a DROID
# default). For LIBERO the two must match (the working libero_sft_dreamzero_5b
# config sets BOTH to 16). Without this, the forward pass asserts:
#   actions.shape[1] / (noise.shape[1]-1) == num_action_per_block // num_frame_per_block
#   (got 64/8=8, expected 24//2=12). With num_action_per_block=16: 16//2=8 == 8.
HYDRA_ARGS="${HYDRA_ARGS} actor.model.num_action_per_block=16"

# Metadata handling: set metadata_json_path when METADATA_PATH is non-empty.
# It now DEFAULTS to /fsx/models/metadata-libero.json (LIBERO libero_sim stats
# generated by generate-metadata.yaml), so the override is passed by default.
# The DreamZero-DROID checkpoint only bundles oxe_droid metadata, so LIBERO SFT
# would fail with a KeyError on embodiment_tag 'libero_sim' without this. Set
# METADATA_PATH="" to fall back to the checkpoint's bundled metadata instead.
# NOTE: metadata_json_path is COMMENTED OUT in the upstream config (not in the
# Hydra struct), so it must be ADDED with the '+' prefix, not overridden.
if [ -n "${METADATA_PATH}" ]; then
    HYDRA_ARGS="${HYDRA_ARGS} +actor.model.metadata_json_path=${METADATA_PATH}"
fi

# Append user-supplied overrides (e.g., HYDRA_OVERRIDES="runner.max_steps=1")
if [ -n "${HYDRA_OVERRIDES:-}" ]; then
    echo "Extra Hydra overrides: ${HYDRA_OVERRIDES}"
    HYDRA_ARGS="${HYDRA_ARGS} ${HYDRA_OVERRIDES}"
fi

echo "=== Launching DreamZero LIBERO SFT (Ray / FSDP2) ==="
echo "Config:    ${CONFIG_NAME}"
echo "Venv:      ${VENV_NAME}"
echo "Model:     ${MODEL_PATH}"
echo "Tokenizer: ${TOKENIZER_PATH}"
echo "Dataset:   ${DATASET_PATH}"
echo "Nodes:     ${NUM_NODES}"
echo "Hydra args: ${HYDRA_ARGS}"

# --config-path is "config", resolved by Hydra relative to the train script's
# own location (examples/sft/), where the SFT configs are baked in.
# HYDRA_ARGS is intentionally word-split.
# shellcheck disable=SC2086
python3 examples/sft/train_vla_sft.py \
    --config-path config \
    --config-name "${CONFIG_NAME}" \
    ${HYDRA_ARGS}
