#!/bin/bash
# setup-directory.sh — Multi-user directory setup for PCS reference architecture.
#
# Single script for both login node (LDAP server) and compute nodes (SSSD client).
# Called from CNG UserData when DirectoryService != "none".
#
# Usage: setup-directory.sh <role>
#   role = "server"  (login node — installs slapd, creates base OUs)
#          "client"  (compute node — installs SSSD, points at LDAP server)
#
# IMPORTANT — single login node only when DirectoryService=OpenLDAP-LoginNode:
#   The OpenLDAP server runs on THE login node and its DB lives on shared
#   /home (OpenZFS). This design assumes exactly ONE login node (server). Do
#   NOT scale the login node group above MinCount=MaxCount=1 with the directory
#   enabled: multiple login nodes would each tag themselves directory-role=server
#   (clients would pick an arbitrary one) and each run a slapd against the same
#   /home/ldap-db MDB files (concurrent-open corruption). For HA multi-server
#   directory, use a managed backend (Simple AD / Managed AD) instead — that is
#   the planned DirectoryService=SimpleAD / ManagedAD extension path.
#
# Environment variables (from UserData):
#   LDAP_DOMAIN_SUFFIX  — e.g. "dc=cluster,dc=internal"
#   LDAP_DOMAIN         — e.g. "cluster.internal" (derived from suffix)
#   LDAP_ADMIN_PASSWORD — auto-generated by UserData (server role only)
#   CLUSTER_ID          — PCS cluster ID (for SSM parameter path)
#   LDAP_SERVER_URI     — e.g. "ldap://10.1.x.x" (client role; empty = discover)
#   DIRECTORY_DNS_IPS   — comma-separated DNS IPs (future SimpleAD; empty = discover login IP)
#   S3_BUCKET           — bucket holding the scripts (server role; to install the
#                         ldap-add-user.sh helper onto /usr/local/bin)
#   S3_KEY_PREFIX       — key prefix for the scripts (default "templates/")

set -euo pipefail

ROLE="${1:-client}"
LDAP_DOMAIN_SUFFIX="${LDAP_DOMAIN_SUFFIX:-dc=cluster,dc=internal}"
LDAP_DOMAIN="${LDAP_DOMAIN:-cluster.internal}"
LDAP_DB_DIR="/home/ldap-db"

export DEBIAN_FRONTEND=noninteractive

# AWS CLI calls below (ssm put-parameter, ec2 describe-instances) pass no
# --region: on EC2 the CLI resolves both credentials and region from the
# instance's IMDS credential provider (it obtains the IMDSv2 token itself, even
# under HttpTokens=required). Reading placement/region with a plain curl would
# need a manual token and return empty without one, so we deliberately let the
# CLI handle it instead of passing a (possibly empty) --region.

echo "[directory] Role: ${ROLE}"
echo "[directory] Domain: ${LDAP_DOMAIN} (${LDAP_DOMAIN_SUFFIX})"

###############################################################################
# apt helpers — at first boot cloud-init's own unattended-upgrades/apt run can
# still hold the dpkg lock, so a bare `apt-get install` fails with
# "Could not get lock /var/lib/dpkg/lock-frontend". Wait for the lock to clear,
# then run apt-get with built-in retries. Mirrors install-enroot-pyxis.sh.
###############################################################################
wait_for_apt_lock() {
    local waited=0
    while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 \
       || fuser /var/lib/dpkg/lock >/dev/null 2>&1 \
       || fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do
        if [ "$waited" -ge 300 ]; then
            echo "[directory] WARNING: dpkg lock still held after ${waited}s; proceeding anyway."
            break
        fi
        echo "[directory] Waiting for apt/dpkg lock to clear (${waited}s)..."
        sleep 10
        waited=$((waited + 10))
    done
}

apt_get() {
    wait_for_apt_lock
    local attempt
    for attempt in 1 2 3; do
        if DEBIAN_FRONTEND=noninteractive apt-get "$@"; then
            return 0
        fi
        echo "[directory] apt-get $* failed (attempt ${attempt}/3); waiting for lock and retrying..."
        wait_for_apt_lock
        sleep 5
    done
    echo "[directory] ERROR: apt-get $* failed after 3 attempts."
    return 1
}

###############################################################################
# SERVER role — login node: install slapd + configure
###############################################################################
setup_server() {
    LDAP_ADMIN_PASSWORD="${LDAP_ADMIN_PASSWORD:?LDAP_ADMIN_PASSWORD must be set}"
    CLUSTER_ID="${CLUSTER_ID:-unknown}"

    echo "[directory-server] Running apt-get update..."
    apt_get update -qq

    echo "[directory-server] Installing slapd + ldap-utils..."
    debconf-set-selections <<EOF
slapd slapd/internal/adminpw password ${LDAP_ADMIN_PASSWORD}
slapd slapd/internal/generated_adminpw password ${LDAP_ADMIN_PASSWORD}
slapd slapd/password2 password ${LDAP_ADMIN_PASSWORD}
slapd slapd/password1 password ${LDAP_ADMIN_PASSWORD}
slapd slapd/domain string ${LDAP_DOMAIN}
slapd shared/organization string PCSCluster
slapd slapd/purge_database boolean false
slapd slapd/move_old_database boolean false
slapd slapd/no_configuration boolean false
EOF
    apt_get install -y slapd ldap-utils

    echo "[directory-server] Configuring LDAP DB on shared storage (${LDAP_DB_DIR})..."
    systemctl stop slapd || true

    # Move DB to shared OpenZFS (/home) if not already there
    if [ ! -d "${LDAP_DB_DIR}" ]; then
        mkdir -p "${LDAP_DB_DIR}"
        if [ -d /var/lib/ldap ] && [ "$(ls -A /var/lib/ldap 2>/dev/null)" ]; then
            cp -a /var/lib/ldap/* "${LDAP_DB_DIR}/"
        fi
        chown -R openldap:openldap "${LDAP_DB_DIR}"
    fi

    # Update slapd DB directory in cn=config
    if [ -d /etc/ldap/slapd.d ]; then
        MDB_LDIF=$(find /etc/ldap/slapd.d -name "olcDatabase*mdb*" -o -name "olcDatabase*hdb*" | head -1)
        if [ -n "$MDB_LDIF" ] && grep -q "olcDbDirectory" "$MDB_LDIF"; then
            sed -i "s|olcDbDirectory:.*|olcDbDirectory: ${LDAP_DB_DIR}|" "$MDB_LDIF"
        fi
    fi

    # AppArmor: allow slapd to access /home/ldap-db
    if [ -f /etc/apparmor.d/usr.sbin.slapd ]; then
        if ! grep -q "${LDAP_DB_DIR}" /etc/apparmor.d/usr.sbin.slapd; then
            sed -i "/\/var\/lib\/ldap\/ r,/a\\  ${LDAP_DB_DIR}/ r," /etc/apparmor.d/usr.sbin.slapd
            sed -i "/\/var\/lib\/ldap\/\*\* rwk,/a\\  ${LDAP_DB_DIR}/** rwk," /etc/apparmor.d/usr.sbin.slapd
            apparmor_parser -r /etc/apparmor.d/usr.sbin.slapd 2>/dev/null || true
        fi
    fi

    chown -R openldap:openldap "${LDAP_DB_DIR}"
    systemctl start slapd
    systemctl enable slapd

    # Wait for slapd
    for i in $(seq 1 10); do
        ldapsearch -x -H ldap://localhost -b "" -s base namingContexts >/dev/null 2>&1 && break
        sleep 1
    done

    echo "[directory-server] Creating base OUs..."
    ldapadd -x -H ldap://localhost -D "cn=admin,${LDAP_DOMAIN_SUFFIX}" -w "${LDAP_ADMIN_PASSWORD}" <<EOF 2>/dev/null || true
dn: ou=People,${LDAP_DOMAIN_SUFFIX}
objectClass: organizationalUnit
ou: People
EOF
    ldapadd -x -H ldap://localhost -D "cn=admin,${LDAP_DOMAIN_SUFFIX}" -w "${LDAP_ADMIN_PASSWORD}" <<EOF 2>/dev/null || true
dn: ou=Groups,${LDAP_DOMAIN_SUFFIX}
objectClass: organizationalUnit
ou: Groups
EOF
    # Default group
    ldapadd -x -H ldap://localhost -D "cn=admin,${LDAP_DOMAIN_SUFFIX}" -w "${LDAP_ADMIN_PASSWORD}" <<EOF 2>/dev/null || true
dn: cn=clusterusers,ou=Groups,${LDAP_DOMAIN_SUFFIX}
objectClass: posixGroup
cn: clusterusers
gidNumber: 3000
EOF

    # Persist admin password — prefer SSM (access-controlled, auditable).
    # No explicit --region: the AWS CLI resolves it from the instance's IMDS
    # credential provider (reading placement/region directly would need an
    # IMDSv2 token).
    if aws ssm put-parameter \
         --name "/pcs/${CLUSTER_ID}/ldap/admin-password" \
         --value "${LDAP_ADMIN_PASSWORD}" \
         --type SecureString \
         --overwrite 2>/dev/null; then
        echo "[directory-server] Admin password stored in SSM: /pcs/${CLUSTER_ID}/ldap/admin-password"
    else
        echo "${LDAP_ADMIN_PASSWORD}" > "${LDAP_DB_DIR}/.admin-password"
        chmod 600 "${LDAP_DB_DIR}/.admin-password"
        chown openldap:openldap "${LDAP_DB_DIR}/.admin-password"
        echo "[directory-server] WARNING: SSM put failed. Password saved to ${LDAP_DB_DIR}/.admin-password"
    fi

    # Install the ldap-add-user helper alongside this script so admins have it
    # on PATH (/usr/local/bin) on the login node. Fetched from the same S3
    # location this script came from (S3_BUCKET/S3_KEY_PREFIX passed by UserData);
    # falls back to a no-op with a hint if those are unset.
    if [ -n "${S3_BUCKET:-}" ]; then
        if aws s3 cp "s3://${S3_BUCKET}/${S3_KEY_PREFIX:-templates/}scripts/ldap-add-user.sh" \
             /usr/local/bin/ldap-add-user.sh 2>/dev/null; then
            chmod 755 /usr/local/bin/ldap-add-user.sh
            echo "[directory-server] Installed helper: /usr/local/bin/ldap-add-user.sh"
        else
            echo "[directory-server] WARNING: could not fetch ldap-add-user.sh from s3://${S3_BUCKET}/${S3_KEY_PREFIX:-templates/}scripts/ — add users with raw ldapadd (see USER-MANAGEMENT.md)."
        fi
    else
        echo "[directory-server] NOTE: S3_BUCKET unset; skipping ldap-add-user.sh install. Add users with raw ldapadd (see USER-MANAGEMENT.md)."
    fi

    # Also configure SSSD on the login node itself (so getent works locally)
    setup_client_internal "ldap://localhost"

    echo "[directory-server] OpenLDAP server ready."
    echo "[directory-server] Admin DN: cn=admin,${LDAP_DOMAIN_SUFFIX}"
}

###############################################################################
# CLIENT role — compute node: install SSSD + configure LDAP provider
###############################################################################
setup_client() {
    # Determine LDAP server URI
    local server_uri="${LDAP_SERVER_URI:-}"

    if [ -z "$server_uri" ]; then
        # Discover login node IP
        if [ -n "${DIRECTORY_DNS_IPS:-}" ]; then
            # Future: SimpleAD — use provided DNS IPs
            server_uri="ldap://${DIRECTORY_DNS_IPS%%,*}"
        else
            # OpenLDAP-LoginNode — discover the directory server's private IP via
            # its EC2 tags (pcs-cluster-id + directory-role=server). The
            # directory-role tag is owned by the multi-user feature and is
            # independent of the monitoring stack's monitoring-role tag. The AWS
            # CLI auto-resolves the region from the instance's IMDS credential
            # provider, so no explicit --region (which would need an IMDSv2 token
            # to read placement/region) is required.
            if [ -z "${CLUSTER_ID:-}" ]; then
                echo "[directory-client] ERROR: CLUSTER_ID is empty; cannot discover directory server. LDAP client not configured."
                return 1
            fi
            local login_ip
            login_ip=$(aws ec2 describe-instances \
                --filters "Name=tag:pcs-cluster-id,Values=${CLUSTER_ID}" \
                          "Name=tag:directory-role,Values=server" \
                          "Name=instance-state-name,Values=running" \
                --query 'Reservations[0].Instances[0].PrivateIpAddress' \
                --output text 2>/dev/null || echo "")
            if [ -z "$login_ip" ] || [ "$login_ip" = "None" ]; then
                echo "[directory-client] ERROR: could not discover directory server IP (CLUSTER_ID=${CLUSTER_ID}, directory-role=server). Check the compute node's IAM role has ec2:DescribeInstances. LDAP client not configured."
                return 1
            fi
            server_uri="ldap://${login_ip}"
        fi
    fi

    setup_client_internal "$server_uri"
}

###############################################################################
# Internal: configure SSSD (shared by server + client roles)
###############################################################################
setup_client_internal() {
    local server_uri="$1"

    echo "[directory-client] Running apt-get update..."
    apt_get update -qq

    echo "[directory-client] Installing SSSD..."
    # sssd-tools provides sss_cache, needed to invalidate the SSSD cache after a
    # user is deleted/modified in LDAP (otherwise the change is not visible until
    # the cache entry's TTL expires — see USER-MANAGEMENT.md "Deleting a user").
    apt_get install -y sssd sssd-tools libpam-sss libnss-sss ldap-utils

    echo "[directory-client] Configuring SSSD (server: ${server_uri})..."
    cat > /etc/sssd/sssd.conf <<EOF
[sssd]
config_file_version = 2
services = nss, pam
domains = ${LDAP_DOMAIN}

[domain/${LDAP_DOMAIN}]
id_provider = ldap
auth_provider = ldap
ldap_uri = ${server_uri}
ldap_search_base = ${LDAP_DOMAIN_SUFFIX}
ldap_user_search_base = ou=People,${LDAP_DOMAIN_SUFFIX}
ldap_group_search_base = ou=Groups,${LDAP_DOMAIN_SUFFIX}
cache_credentials = true
enumerate = true
default_shell = /bin/bash
fallback_homedir = /home/%u
min_id = 1001
max_id = 60000
EOF
    chmod 600 /etc/sssd/sssd.conf

    # Enable pam_mkhomedir
    if ! grep -q pam_mkhomedir /etc/pam.d/common-session; then
        echo "session optional pam_mkhomedir.so skel=/etc/skel umask=0022" >> /etc/pam.d/common-session
    fi

    # Configure NSS
    sed -i 's/^passwd:.*/passwd:         files systemd sss/' /etc/nsswitch.conf
    sed -i 's/^group:.*/group:          files systemd sss/' /etc/nsswitch.conf
    sed -i 's/^shadow:.*/shadow:         files sss/' /etc/nsswitch.conf

    systemctl enable sssd
    systemctl restart sssd

    echo "[directory-client] SSSD configured. Server: ${server_uri}"
}

###############################################################################
# Main
###############################################################################
case "$ROLE" in
    server)
        setup_server
        ;;
    client)
        setup_client
        ;;
    *)
        echo "Usage: $0 <server|client>"
        exit 1
        ;;
esac
