#!/bin/bash
# setup-directory.sh — Multi-user directory setup for PCS reference architecture.
#
# Single script for both login node (LDAP server) and compute nodes (SSSD client).
# Called from CNG UserData when DirectoryService != "none".
#
# Usage: setup-directory.sh <role>
#   role = "server"  (login node — installs slapd, creates base OUs)
#          "client"  (compute node — installs SSSD, points at LDAP server)
#
# Environment variables (from UserData):
#   LDAP_DOMAIN_SUFFIX  — e.g. "dc=cluster,dc=internal"
#   LDAP_DOMAIN         — e.g. "cluster.internal" (derived from suffix)
#   LDAP_ADMIN_PASSWORD — auto-generated by UserData (server role only)
#   CLUSTER_ID          — PCS cluster ID (for SSM parameter path)
#   LDAP_SERVER_URI     — e.g. "ldap://10.1.x.x" (client role; empty = discover)
#   DIRECTORY_DNS_IPS   — comma-separated DNS IPs (future SimpleAD; empty = discover login IP)

set -euo pipefail

ROLE="${1:-client}"
LDAP_DOMAIN_SUFFIX="${LDAP_DOMAIN_SUFFIX:-dc=cluster,dc=internal}"
LDAP_DOMAIN="${LDAP_DOMAIN:-cluster.internal}"
LDAP_DB_DIR="/home/ldap-db"

export DEBIAN_FRONTEND=noninteractive

echo "[directory] Role: ${ROLE}"
echo "[directory] Domain: ${LDAP_DOMAIN} (${LDAP_DOMAIN_SUFFIX})"

###############################################################################
# SERVER role — login node: install slapd + configure
###############################################################################
setup_server() {
    LDAP_ADMIN_PASSWORD="${LDAP_ADMIN_PASSWORD:?LDAP_ADMIN_PASSWORD must be set}"
    CLUSTER_ID="${CLUSTER_ID:-unknown}"

    echo "[directory-server] Running apt-get update..."
    apt-get update -qq

    echo "[directory-server] Installing slapd + ldap-utils..."
    debconf-set-selections <<EOF
slapd slapd/internal/adminpw password ${LDAP_ADMIN_PASSWORD}
slapd slapd/internal/generated_adminpw password ${LDAP_ADMIN_PASSWORD}
slapd slapd/password2 password ${LDAP_ADMIN_PASSWORD}
slapd slapd/password1 password ${LDAP_ADMIN_PASSWORD}
slapd slapd/domain string ${LDAP_DOMAIN}
slapd shared/organization string PCSCluster
slapd slapd/purge_database boolean false
slapd slapd/move_old_database boolean false
slapd slapd/no_configuration boolean false
EOF
    apt-get install -y slapd ldap-utils

    echo "[directory-server] Configuring LDAP DB on shared storage (${LDAP_DB_DIR})..."
    systemctl stop slapd || true

    # Move DB to shared OpenZFS (/home) if not already there
    if [ ! -d "${LDAP_DB_DIR}" ]; then
        mkdir -p "${LDAP_DB_DIR}"
        if [ -d /var/lib/ldap ] && [ "$(ls -A /var/lib/ldap 2>/dev/null)" ]; then
            cp -a /var/lib/ldap/* "${LDAP_DB_DIR}/"
        fi
        chown -R openldap:openldap "${LDAP_DB_DIR}"
    fi

    # Update slapd DB directory in cn=config
    if [ -d /etc/ldap/slapd.d ]; then
        MDB_LDIF=$(find /etc/ldap/slapd.d -name "olcDatabase*mdb*" -o -name "olcDatabase*hdb*" | head -1)
        if [ -n "$MDB_LDIF" ] && grep -q "olcDbDirectory" "$MDB_LDIF"; then
            sed -i "s|olcDbDirectory:.*|olcDbDirectory: ${LDAP_DB_DIR}|" "$MDB_LDIF"
        fi
    fi

    # AppArmor: allow slapd to access /home/ldap-db
    if [ -f /etc/apparmor.d/usr.sbin.slapd ]; then
        if ! grep -q "${LDAP_DB_DIR}" /etc/apparmor.d/usr.sbin.slapd; then
            sed -i "/\/var\/lib\/ldap\/ r,/a\\  ${LDAP_DB_DIR}/ r," /etc/apparmor.d/usr.sbin.slapd
            sed -i "/\/var\/lib\/ldap\/\*\* rwk,/a\\  ${LDAP_DB_DIR}/** rwk," /etc/apparmor.d/usr.sbin.slapd
            apparmor_parser -r /etc/apparmor.d/usr.sbin.slapd 2>/dev/null || true
        fi
    fi

    chown -R openldap:openldap "${LDAP_DB_DIR}"
    systemctl start slapd
    systemctl enable slapd

    # Wait for slapd
    for i in $(seq 1 10); do
        ldapsearch -x -H ldap://localhost -b "" -s base namingContexts >/dev/null 2>&1 && break
        sleep 1
    done

    echo "[directory-server] Creating base OUs..."
    ldapadd -x -H ldap://localhost -D "cn=admin,${LDAP_DOMAIN_SUFFIX}" -w "${LDAP_ADMIN_PASSWORD}" <<EOF 2>/dev/null || true
dn: ou=People,${LDAP_DOMAIN_SUFFIX}
objectClass: organizationalUnit
ou: People
EOF
    ldapadd -x -H ldap://localhost -D "cn=admin,${LDAP_DOMAIN_SUFFIX}" -w "${LDAP_ADMIN_PASSWORD}" <<EOF 2>/dev/null || true
dn: ou=Groups,${LDAP_DOMAIN_SUFFIX}
objectClass: organizationalUnit
ou: Groups
EOF
    # Default group
    ldapadd -x -H ldap://localhost -D "cn=admin,${LDAP_DOMAIN_SUFFIX}" -w "${LDAP_ADMIN_PASSWORD}" <<EOF 2>/dev/null || true
dn: cn=clusterusers,ou=Groups,${LDAP_DOMAIN_SUFFIX}
objectClass: posixGroup
cn: clusterusers
gidNumber: 3000
EOF

    # Persist admin password — prefer SSM (access-controlled, auditable)
    REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/region)
    if aws ssm put-parameter \
         --name "/pcs/${CLUSTER_ID}/ldap/admin-password" \
         --value "${LDAP_ADMIN_PASSWORD}" \
         --type SecureString \
         --overwrite \
         --region "${REGION}" 2>/dev/null; then
        echo "[directory-server] Admin password stored in SSM: /pcs/${CLUSTER_ID}/ldap/admin-password"
    else
        echo "${LDAP_ADMIN_PASSWORD}" > "${LDAP_DB_DIR}/.admin-password"
        chmod 600 "${LDAP_DB_DIR}/.admin-password"
        chown openldap:openldap "${LDAP_DB_DIR}/.admin-password"
        echo "[directory-server] WARNING: SSM put failed. Password saved to ${LDAP_DB_DIR}/.admin-password"
    fi

    # Also configure SSSD on the login node itself (so getent works locally)
    setup_client_internal "ldap://localhost"

    echo "[directory-server] OpenLDAP server ready."
    echo "[directory-server] Admin DN: cn=admin,${LDAP_DOMAIN_SUFFIX}"
}

###############################################################################
# CLIENT role — compute node: install SSSD + configure LDAP provider
###############################################################################
setup_client() {
    # Determine LDAP server URI
    local server_uri="${LDAP_SERVER_URI:-}"

    if [ -z "$server_uri" ]; then
        # Discover login node IP
        if [ -n "${DIRECTORY_DNS_IPS:-}" ]; then
            # Future: SimpleAD — use provided DNS IPs
            server_uri="ldap://${DIRECTORY_DNS_IPS%%,*}"
        else
            # OpenLDAP-LoginNode — discover via EC2 tag query
            local region
            region=$(curl -s http://169.254.169.254/latest/meta-data/placement/region)
            local login_ip
            login_ip=$(aws ec2 describe-instances --region "${region}" \
                --filters "Name=tag:pcs-cluster-id,Values=${CLUSTER_ID:-}" \
                          "Name=tag:monitoring-role,Values=login" \
                          "Name=instance-state-name,Values=running" \
                --query 'Reservations[0].Instances[0].PrivateIpAddress' \
                --output text 2>/dev/null || echo "")
            if [ -z "$login_ip" ] || [ "$login_ip" = "None" ]; then
                echo "[directory-client] ERROR: could not discover login node IP. LDAP client not configured."
                return 1
            fi
            server_uri="ldap://${login_ip}"
        fi
    fi

    setup_client_internal "$server_uri"
}

###############################################################################
# Internal: configure SSSD (shared by server + client roles)
###############################################################################
setup_client_internal() {
    local server_uri="$1"

    echo "[directory-client] Running apt-get update..."
    apt-get update -qq

    echo "[directory-client] Installing SSSD..."
    apt-get install -y sssd libpam-sss libnss-sss ldap-utils

    echo "[directory-client] Configuring SSSD (server: ${server_uri})..."
    cat > /etc/sssd/sssd.conf <<EOF
[sssd]
config_file_version = 2
services = nss, pam
domains = ${LDAP_DOMAIN}

[domain/${LDAP_DOMAIN}]
id_provider = ldap
auth_provider = ldap
ldap_uri = ${server_uri}
ldap_search_base = ${LDAP_DOMAIN_SUFFIX}
ldap_user_search_base = ou=People,${LDAP_DOMAIN_SUFFIX}
ldap_group_search_base = ou=Groups,${LDAP_DOMAIN_SUFFIX}
cache_credentials = true
enumerate = true
default_shell = /bin/bash
fallback_homedir = /home/%u
min_id = 1001
max_id = 60000
EOF
    chmod 600 /etc/sssd/sssd.conf

    # Enable pam_mkhomedir
    if ! grep -q pam_mkhomedir /etc/pam.d/common-session; then
        echo "session optional pam_mkhomedir.so skel=/etc/skel umask=0022" >> /etc/pam.d/common-session
    fi

    # Configure NSS
    sed -i 's/^passwd:.*/passwd:         files systemd sss/' /etc/nsswitch.conf
    sed -i 's/^group:.*/group:          files systemd sss/' /etc/nsswitch.conf
    sed -i 's/^shadow:.*/shadow:         files sss/' /etc/nsswitch.conf

    systemctl enable sssd
    systemctl restart sssd

    echo "[directory-client] SSSD configured. Server: ${server_uri}"
}

###############################################################################
# Main
###############################################################################
case "$ROLE" in
    server)
        setup_server
        ;;
    client)
        setup_client
        ;;
    *)
        echo "Usage: $0 <server|client>"
        exit 1
        ;;
esac
