# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
# @package _global_
# Console-only logging (no MLflow dependency)
tracking:
  logger:
    - console
